[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Front

## Tools
> fillColor=`#CCCC00`


### Packmanager
> fillColor=`#CCCC00`


#### npm
> fillColor=`#CCCC00`


#### yarn

### module loaders

#### webpack

## Javascript
> leftSide=`true`


## library/framework
> fillColor=`#CCCC00`,leftSide=`true`


### react
> fillColor=`#CCCC00`


### vue

### angular

### backbone

### ember

## ui

### framework
> fillColor=`#CCCC00`


#### antd
> fillColor=`#CCCC00`


#### mui
> fillColor=`#CCCC00`


#### shakra

## ServerSide
> fillColor=`#CCCC00`,leftSide=`true`


### NextJS
> fillColor=`#CCCC00`


### NestJS
